// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package datasource

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatNetworkConfig is an auto-generated flat version of NetworkConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatNetworkConfig struct {
	PackerBuildName     *string           `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name"`
	PackerBuilderType   *string           `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type"`
	PackerCoreVersion   *string           `mapstructure:"packer_core_version" cty:"packer_core_version" hcl:"packer_core_version"`
	PackerDebug         *bool             `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug"`
	PackerForce         *bool             `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force"`
	PackerOnError       *string           `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error"`
	PackerUserVars      map[string]string `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables"`
	PackerSensitiveVars []string          `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables"`
	BaseURL             *string           `mapstructure:"base_url" required:"false" cty:"base_url" hcl:"base_url"`
	ClientID            *string           `mapstructure:"client_id" required:"true" cty:"client_id" hcl:"client_id"`
	Token               *string           `mapstructure:"token" required:"true" cty:"token" hcl:"token"`
	CloudID             *string           `mapstructure:"cloud_id" required:"false" cty:"cloud_id" hcl:"cloud_id"`
	Name                *string           `mapstructure:"name" required:"true" cty:"name" hcl:"name"`
	TenantID            *string           `mapstructure:"tenant_id" required:"false" cty:"tenant_id" hcl:"tenant_id"`
}

// FlatMapstructure returns a new FlatNetworkConfig.
// FlatNetworkConfig is an auto-generated flat version of NetworkConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*NetworkConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatNetworkConfig)
}

// HCL2Spec returns the hcl spec of a NetworkConfig.
// This spec is used by HCL to read the fields of NetworkConfig.
// The decoded values from this spec will then be applied to a FlatNetworkConfig.
func (*FlatNetworkConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"packer_build_name":          &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"packer_builder_type":        &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"packer_core_version":        &hcldec.AttrSpec{Name: "packer_core_version", Type: cty.String, Required: false},
		"packer_debug":               &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"packer_force":               &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"packer_on_error":            &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"packer_user_variables":      &hcldec.AttrSpec{Name: "packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"packer_sensitive_variables": &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"base_url":                   &hcldec.AttrSpec{Name: "base_url", Type: cty.String, Required: false},
		"client_id":                  &hcldec.AttrSpec{Name: "client_id", Type: cty.String, Required: false},
		"token":                      &hcldec.AttrSpec{Name: "token", Type: cty.String, Required: false},
		"cloud_id":                   &hcldec.AttrSpec{Name: "cloud_id", Type: cty.String, Required: false},
		"name":                       &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"tenant_id":                  &hcldec.AttrSpec{Name: "tenant_id", Type: cty.String, Required: false},
	}
	return s
}

// FlatNetworkDatasourceOutput is an auto-generated flat version of NetworkDatasourceOutput.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatNetworkDatasourceOutput struct {
	ID   *string `mapstructure:"id" cty:"id" hcl:"id"`
	Type *string `mapstructure:"type" cty:"type" hcl:"type"`
}

// FlatMapstructure returns a new FlatNetworkDatasourceOutput.
// FlatNetworkDatasourceOutput is an auto-generated flat version of NetworkDatasourceOutput.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*NetworkDatasourceOutput) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatNetworkDatasourceOutput)
}

// HCL2Spec returns the hcl spec of a NetworkDatasourceOutput.
// This spec is used by HCL to read the fields of NetworkDatasourceOutput.
// The decoded values from this spec will then be applied to a FlatNetworkDatasourceOutput.
func (*FlatNetworkDatasourceOutput) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"id":   &hcldec.AttrSpec{Name: "id", Type: cty.String, Required: false},
		"type": &hcldec.AttrSpec{Name: "type", Type: cty.String, Required: false},
	}
	return s
}
