// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package datasource

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatTemplateConfig is an auto-generated flat version of TemplateConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatTemplateConfig struct {
	PackerBuildName     *string           `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name"`
	PackerBuilderType   *string           `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type"`
	PackerCoreVersion   *string           `mapstructure:"packer_core_version" cty:"packer_core_version" hcl:"packer_core_version"`
	PackerDebug         *bool             `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug"`
	PackerForce         *bool             `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force"`
	PackerOnError       *string           `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error"`
	PackerUserVars      map[string]string `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables"`
	PackerSensitiveVars []string          `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables"`
	BaseURL             *string           `mapstructure:"base_url" required:"false" cty:"base_url" hcl:"base_url"`
	ClientID            *string           `mapstructure:"client_id" required:"true" cty:"client_id" hcl:"client_id"`
	Token               *string           `mapstructure:"token" required:"true" cty:"token" hcl:"token"`
	MostRecent          *bool             `mapstructure:"most_recent" required:"false" cty:"most_recent" hcl:"most_recent"`
	Name                *string           `mapstructure:"name" required:"true" cty:"name" hcl:"name"`
}

// FlatMapstructure returns a new FlatTemplateConfig.
// FlatTemplateConfig is an auto-generated flat version of TemplateConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*TemplateConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatTemplateConfig)
}

// HCL2Spec returns the hcl spec of a TemplateConfig.
// This spec is used by HCL to read the fields of TemplateConfig.
// The decoded values from this spec will then be applied to a FlatTemplateConfig.
func (*FlatTemplateConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"packer_build_name":          &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"packer_builder_type":        &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"packer_core_version":        &hcldec.AttrSpec{Name: "packer_core_version", Type: cty.String, Required: false},
		"packer_debug":               &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"packer_force":               &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"packer_on_error":            &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"packer_user_variables":      &hcldec.AttrSpec{Name: "packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"packer_sensitive_variables": &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"base_url":                   &hcldec.AttrSpec{Name: "base_url", Type: cty.String, Required: false},
		"client_id":                  &hcldec.AttrSpec{Name: "client_id", Type: cty.String, Required: false},
		"token":                      &hcldec.AttrSpec{Name: "token", Type: cty.String, Required: false},
		"most_recent":                &hcldec.AttrSpec{Name: "most_recent", Type: cty.Bool, Required: false},
		"name":                       &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
	}
	return s
}

// FlatTemplateDatasourceOutput is an auto-generated flat version of TemplateDatasourceOutput.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatTemplateDatasourceOutput struct {
	ID           *string `mapstructure:"id" cty:"id" hcl:"id"`
	Name         *string `mapstructure:"name" cty:"name" hcl:"name"`
	CreationDate *string `mapstructure:"creation_date" cty:"creation_date" hcl:"creation_date"`
}

// FlatMapstructure returns a new FlatTemplateDatasourceOutput.
// FlatTemplateDatasourceOutput is an auto-generated flat version of TemplateDatasourceOutput.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*TemplateDatasourceOutput) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatTemplateDatasourceOutput)
}

// HCL2Spec returns the hcl spec of a TemplateDatasourceOutput.
// This spec is used by HCL to read the fields of TemplateDatasourceOutput.
// The decoded values from this spec will then be applied to a FlatTemplateDatasourceOutput.
func (*FlatTemplateDatasourceOutput) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"id":            &hcldec.AttrSpec{Name: "id", Type: cty.String, Required: false},
		"name":          &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"creation_date": &hcldec.AttrSpec{Name: "creation_date", Type: cty.String, Required: false},
	}
	return s
}
